name: overlay_demo
description: overlay demo

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  system_alert_window: ^1.1.1
  firebase_messaging: ^11.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

scripts:
  win: flutter run -d windows
  device: flutter run -d R58M56CMENJ
  android: flutter run -d emulator-5554 
  rebuild: pub run build_runner build --delete-conflicting-outputs